### ISSUE TITLE
Display version number in UI when ready

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm-devtools#20]
Vue dev tools do this. I think it's quite nice:
 
<img width="1280" alt="screen shot 2017-06-28 at 8 21 37 am" src="https://user-images.githubusercontent.com/590904/27636730-dad4a7b6-5bda-11e7-86f3-221612449973.png">

**Comment by prayash** [comment]
Would we have to add a method inside of the main Microcosm library to grab the version number or is there another way to do this?

**Comment by nhunzaker** [comment]
I think that's what we'd need to do. Curious what Vue is doing. It might just be an environment variable on that compiles on build.

**Comment by prayash** [comment]
Ahh yes looks like they have an env variable, but it can also parse the package.json version like so: 
```javascript
const version = process.env.VERSION || require('../package.json').version
```

And in their devtools they simply pass that variable over via the bridge:
```javascript
bridge.log('backend ready.')
bridge.send('ready', hook.Vue.version)
```

**Comment by nhunzaker** [comment]
Let's actually not worry about this right now.
